version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 24030911
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - secure-chat-net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: secure_chat_user
      RABBITMQ_DEFAULT_PASS: 123456789
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - secure-chat-net

volumes:
  mongodb_data_container:

  rabbitmq_data:
    driver: local

networks:
  secure-chat-net:
    driver: bridge